### ISSUE TITLE
Inconsistent error messages when incrementing null terminated array pointers with checked type and itype

### ISSUE THREAD

**Issue by john-h-kastner** [microsoft/checkedc-clang#1105]
In the first function below a clang emits a warning about the increment, but in the second function, the warning becomes an error. I would expect that both functions give the same warning, or perhaps the itype case should not even emit a warning since it's being used outside of a checked region. In any case, having stricter checking for an itype seems wrong.

As a workaround, changing the second protoype to `void test1(char *s : itype(_Nt_array_ptr<char>) bounds(unknown))` seems to make things work how I expect (no error or warning from the itype). Alternatively, placing it in a checked scope (`_Checked void test1(char *s : itype(_Nt_array_ptr<char>))`) causes it to give the same warning as the fully checked type.  The error is only present when `s` is  `itype(_Nt_array_ptr<char>)`. Changing it to `itype(_Array_ptr<char>)` or `itype(_Ptr<char>)` gets rid of the error without any warning. 

```c
void test0(_Nt_array_ptr<char> s) {
  s++;
}
void test1(char *s : itype(_Nt_array_ptr<char>)) {
  s++;
}
```

```
nt.c:2:3: warning: cannot prove declared bounds for 's' are valid after increment [-Wcheck-bounds-decls-unchecked-scope]
  s++;
  ^~~
nt.c:1:32: note: (expanded) declared bounds are 'bounds(s, s + 0)'
void test0(_Nt_array_ptr<char> s) {
                               ^
nt.c:2:3: note: (expanded) inferred bounds are 'bounds(s - 1, s - 1 + 0)'
  s++;
  ^
nt.c:5:3: error: inferred bounds for 's' are unknown after increment
  s++;
  ^~~
nt.c:4:18: note: (expanded) declared bounds are 'bounds(s, s + 0)'
void test1(char *s : itype(_Nt_array_ptr<char>)) {
                 ^
nt.c:5:3: note: lost the value of the expression 's' which is used in the (expanded) inferred bounds 'bounds(s, s + 0)' of 's'
  s++;
  ^
1 warning and 1 error generated.
```

**Comment by kkjeer** [comment]
Hi @john-h-kastner, we plan to look into ways to improve the error messages for cases like these.

The difference in bounds checking behavior in `test0` and `test1` is due to the respective types of `s` in these functions. `s` has type `_Nt_array_ptr<char>` in `test0` and type `char *` in `test1` (since `test1` is in an unchecked scope). The type of `s` affects whether `s` has an original value before it is modified in the statement `s++`.

In `test0`, `s` is a checked pointer of type `_Nt_array_ptr<char>`. Since the right-hand side `s + 1` of the (implied) assignment `s = s + 1` is checked pointer arithmetic, `s` has the original value `s - 1` before the assignment. This original value is used to compute the inferred bounds `bounds(s - 1, s - 1 + 0)` for s after the statement `s++`.

Since `test1` is in an unchecked scope, the compiler treats `s` as an unchecked pointer of type `char *`. For unchecked pointer arithmetic `s + 1`, `s` has no original value before the assignment `s = s + 1`. This results in the inferred bounds of `s` being `bounds(unknown)` after the statement `s++`.

In both `test0` and `test1`, `s` has the implicit declared bounds of `bounds(s, s + 0)`. This is due to the `_Nt_array_ptr<char>` type or itype for `s`. If the declared bounds of `s` are `bounds(unknown)`, then there are no bounds checking errors or warnings, since all bounds imply `bounds(unknown)`. If `s` explicitly has declared bounds of `bounds(unknown)`, then the declared bounds of `s` are `bounds(unknown)`. If `s` is of type `_Array_ptr<char>` with no explicit declared bounds, then the declared bounds of `s` are `bounds(unknown)`.

**Comment by kkjeer** [comment]
Closing this issue in favor of #1123.
