### ISSUE TITLE
Where can we find function _Dynamic_check() 

### ISSUE THREAD

**Issue by zhangyibobobo** [Microsoft/checkedc-clang#184]
Dear Sir:
Now we can see this test function:
void f1(int i) {
  // This is expected fail at runtime
  dynamic_check(i < 30);
}

int main(void) {
  f1(50);

  return 0;
}

But we can't find function _Dynamic_check() , can you tell me where we can find this, or can you show to me or tell me how dynaminc check work?

And what's the next and future plan? 

Thanks!
Best Wishes!

**Comment by lenary** [comment]
The `void _Dynamic_check(int)` function has been added as a compiler builtin. I believe it is only processed if you have passed `-fcheckedc-extension` to our fork of clang in the compile step. 

As for how it works, we evaluate the passed integer as a condition. If that condition is false, we branch to a trap instruction (which terminates the process), otherwise we branch to the code immediately following the `_Dynamic_check(condition)` call. There are some restrictions placed by the compiler on the expression within the conditional: it may not have side effects.
