### ISSUE TITLE
Improve error recovery for bounds expressions parsing

### ISSUE THREAD

**Issue by dtarditi** [Microsoft/checkedc-clang#188]
We do a poor job of error recovery when the keyword that starts a bounds expression is misspelled.   This leads to problematic error messages, particularly when rel_align is involved.   We should improve the error recover for bounds expressions.

**Comment by jijoongmoon** [comment]
I also found that there is assert error after ParseBoundsExpressionOrInteropType() in DeferredParseBoundsExpression(). This assert is happened when the relative bounds clause is typo like below,
bounds(arr, arr+2) rel_alve(char).
After parsing the bounds expression, the ResultEpxr is not invalid but rel_alive is not the right.
This is because I push back without checking if the token is relative alignment or not.
I will fix it including this pull request.

**Comment by jijoongmoon** [comment]
We also found the clang error situation in the code below:

void a(int c, int d) **_xxxxx_**{}
extern int cLan**_;_**
void f(){
  int b = **_cLan_**;
}

In this case, we can see that "undeclared identifier 'cLan' error, although we define it as extern.
This is because clang parser (SkipUntil) goes to the semi after the cLan when there is an error at function definition such as '**_xxxxx_**'.
There is same situation in rel_align as in code below.

array_ptr<int> f1(array_ptr<int>arr : count(5)) : bounds( arr, arr+1 ) **_rel_alive_**(char) {}
extern int cLan**_;_**
extern array_ptr<int> f : byte_count(**_cLan_** * sizeof(int));

We can see the "undefined error of cLan". Because parser skip to the nearest semi which is the one after cLan. The typo of rel_align "**_rel_alive_**" cause of it. That's why we can see undefined error. 
I wonder if we have to handle this kind of situation? I think it looks like clang parsing error rather than our parsing error situation.

**Comment by dtarditi** [comment]
I believe we do better job now.  I looked at a variant of the code snippet that @jijoongmoon described:
```
_Array_ptr<int> f1(_Array_ptr<int> arr : count(5)) : bounds(arr, arr + 1) rel_alive(char) { return arr; }
extern int cLan;
extern _Array_ptr<int> f : byte_count(cLan * sizeof(int));
```
Here is the error message:
```
tmp.c:1:75: error: expected function body after function declarator
_Array_ptr<int> f1(_Array_ptr<int> arr : count(5)) : bounds(arr, arr + 1) rel_alive(char) { return arr; }
                                                                          ^
tmp.c:3:39: error: use of undeclared identifier 'cLan'
extern _Array_ptr<int> f : byte_count(cLan * sizeof(int));
```
I don't think we need to do anything for this case.  The error message is pointing at the problematic token, so a programmer will know what to fix.     The fact that clang generates a spurious error message isn't really a Checked C implementation issue, other than we are encouraging programmers to write some code after the parameter list that could be mistyped..  clang is looking to parse a function body, which rel_aligb does not start.   The clang code skips to the first ';'.   This isn't error recovery code that we wrote.   

We could try to have some error recovery code that looks for typos involving Checked C keywords and fixes them.   That is much lower priority than other work we need to do for the Checked C extension. It is not worth tracking as a  work item.
