### ISSUE TITLE
Change types produced by address-of operator in checked blocks.

### ISSUE THREAD

**Issue by dtarditi** [Microsoft/checkedc-clang#201]
This is describe in Section 2.4.1 of the Checked C specification.

**Comment by wonsubkim** [comment]
I have a question about address-of operator
Let's look at below example to verify generated expression

```
int a checked[10];
array_ptr<int> b;
int i;

ptr<int> x = &a[i];
ptr<int> y = &b[0];
ptr<int> z = &i;
```
For current implementation, the address-of operator always produce unchecked pointer type
However, checked scope will change types according to checked property 
For example, `ptr<int> x = &a[i];`
Although a is checked array type, &a[i] produces unchecked pointer type and it generates default implicit cast operation after that
As a result of that, generated expression is as follows
**ImplicitCastExpr _Ptr<int> <BitCast> (UnaryOperator int * prefix &)**
If checked scope changes type as proper checked pointer type, expected result is as follows
**UnaryOperator _Ptr<int> prefix &**

Therefore, default implicit cast operator can be removed if possible
How about your opinion?

**Comment by wonsubkim** [comment]
In specification (ch2.4.1), it describes a rule for the address-of operator as follows
_In checked block, if an address-of operator (&) applied to an lvalue expression, the address-of operator produces a value of type ptr<T>
Otherwise, the address-of operator produces a value of type (T *)_

I have some question about this
```
checked {
int a checked[10];
array_ptr<int> b;
int i;

ptr<int> x = &a[i]; 
ptr<int> y = &b[0];
ptr<int> z = &i;

array_ptr<int> ax = &a[i]; // wonder if address-of operator output is _Ptr or _Array_ptr
array_ptr<int> ay = &b[0]; // wonder if address-of operator output is _Ptr or _Array_ptr
array_ptr<int> az = &i; // think that address-of operator output is _Ptr
}
```
In assignment of ptr<int> x, y, z, since the result of address-of operator of lvalue is _Ptr<int>, there is no error
However, in next 3 assignments of array_ptr<int> ax, ay, az, there are incompatible errors
because address-of operator result is _Ptr<int> type but LHS is _Array_ptr<int>

However, a is checked array type and b is checked array pointer type
since a is checked array type, I think that address-of operator result is checked array pointer type
since b is checked pointer type, I think that address-of operator result is also checked array pointer type
In consequence, when address-of operator is applied to Lvalue, 

Can you explain this?

**Comment by dtarditi** [comment]
Thank you for pointing out this issue.  I think the address-of operator in checked blocks should produce an array_ptr type, not a ptr type.  

In Section 5.2.3, we will need to add rules for implicit casts between checked pointer types.   We currently do not allow array_ptr<T> to be converted to ptr<T>, which will we need to allow.  It also makes sense to allow ptr<T> to be converted implicitly to array_ptr<T>, although this is less useful.

**Comment by wonsubkim** [comment]
Yes, I agree that it is required to change implicit casting rule between checked pointer types.
Since checked-c will require explicit pointer type casting between checked pointer types under current constraints, I think that it is better to change constraints for incompatible pointer type.

However, I did not understand why address-of operator should produce array_ptr not ptr type
If implicit casting rule between checked pointer types is added, I think that it is no matter which checked pointer type address-of operator in checked scope produces.

Can you explain it?

**Comment by dtarditi** [comment]
There is a difference between array_ptr and ptr.  With a pointer _p_ of ptr type, a programmer can always write to the location pointed to by _p_.   This means that when _p_ is created, it must always be in bounds.   With an array_ptr, the pointer doesn't have to be in bounds.

With the address-of operator, you can create a pointer that is out-of-bounds.   For example:
```
int checked arr[10];
  ... &arr[11];
```
It follows that we should not use ptr as the type of the resulting expression.  We'd have to be able to prove that the pointer is bounds at the point where the address is taken.

A similar problem could occur for &*p, where _p_ is an array_ptr.   The pointer _p_ may not be in range.

**Comment by dtarditi** [comment]
This work is complete.
