### ISSUE TITLE
Implement runtime checking for dynamic_bounds_cast

### ISSUE THREAD

**Issue by dtarditi** [Microsoft/checkedc-clang#256]
The dynamic_bounds_cast operator requires runtime checks of bounds.    I think this runtime checking should be inserted during the lowering to clang IR.

**Comment by dtarditi** [comment]
Correct the name of the operator: it is dynamic_bounds_cast.

**Comment by wonsubkim** [comment]
I think that it works as follows
- DynamicBoundsCast/AssumeBoundsCast kinds exist
- For DynamicBoundsCast casting kind, CodeGen emits dynamic bounds check code
  - BoundsCastExpr has bounds for bounds casting operation - bounds(castlb, castub)
  - BoundsCastExpr has inferred bounds for source expression - bounds(lb, ub)
  - It inserts Dynamic_check(lb <= castlb && castub <= ub)
- How does the type casting works?
  - In C++ dynamic_cast, it generates code to call dynamic cast function call
  - In checked-c, how does it work except for generating dynamic check?

**Comment by lenary** [comment]
@wonsubkim I can't say how code generation works for the casting itself, but I can help you with finding the code you need to call.

You want to call [`CGF.EmitDynamicBoundsCheck(const Address PtrAddr, const BoundsExpr *Bounds)`](https://github.com/Microsoft/checkedc-clang/blob/master/lib/CodeGen/CGDynamicCheck.cpp#L75), using the pointer you're casting and the BoundsExpr you have. Sometimes you may not have the pointer as an `Address` object (it may be an LValue, Clang has weird conventions around this). There are methods on the LValue struct to turn it into an address, but you have to use the right one for the kind of LValue you have (there's an enum in the LValue which tells you).

This method will do all the calculation for you. You can see it being used a lot in `CGExpr.cpp`.

**Comment by wonsubkim** [comment]
I am now preparing runtime check insertion for bounds cast
After current bounds casting parsing implementation is completed, I will do PR for this issue

I think that dynamic_bounds_cast code generation consists of two parts
1. if required, dynamic bounds check insertion
2. explicit type casting code generation

For code generation of dynamic check, I refer to EmitDynamicBoundsCheck but it will be little bit different since it requires inferred source bounds not PtrAddr
I plan to implement as follows
`EmitDyanmicBoundsCheck(const BoundsExpr *DynamicBounds, const BoundsExpr *SrcBounds)`

DynamicBounds is bounds generated by bounds cast operator, `bounds(castlb, castub)`
SourceBounds is bounds inferred from source expression, `bounds(lb, ub)`
It will produce dynamnic check, `dynamic_check(lb <= castlb && castub <=ub)`

I think that dynamic_bounds_cast is same as explicit type casting except for generating bounds information.
So, I plan to implement type casting code generation based on explicit type casting expression.

**Comment by dtarditi** [comment]
This work is complete, except for handling requirements related to relative alignment.  That is covered by feature #330.
