### ISSUE TITLE
Conversions between pointers to objects of different types

### ISSUE THREAD

**Issue by saeednj** [Microsoft/checkedc-clang#356]
In the section 5.1.4 of the specification (Non-Examples), examples of inappropriate casting between unchecked and checked pointers is given.

The sample code in section 5.1.4 is:
```
int x = 0;
// fails to check: source not large enough
array_ptr<int> pax : count(5) = (array_ptr<int>) &x;
```
but the following code compiles fine and prints "0":
```
#include <stdio.h>
int main()
{
    int x = 10;
    _Array_ptr<int> pa : count(5) = (_Array_ptr<int>)&x;
    printf("%d\n", pa[1]);
    return 0;
}
```
Is this a bug, missing implementation or does "fails to check" means something that I misunderstood (not a compile error)?

**Comment by dtarditi** [comment]
The static checking of bounds declarations is a work-in-progress.   It's a warning flag (-Wcheck-bounds-decls) that is off by default and only done for assignments.  I just created pull request (PR #358)  that extends it to declarations with initializers.

It is off by default because the checking is not very powerful.  It would generate lots of warnings.   The plan is to strengthen the checking to the point where eventually it will be turned into an error message.    The checking has to prove that the inferred bounds for the right-hand of an assignment (or an initializer) imply the declared bounds for the left-hand of an assignment (or the  declared bounds for a variable).   Right now, we can only check that the inferred bounds declarations are syntactically identical and simple cases involving bounds(none)/bounds(any).  

I'm working on extending the checking to understand when variables hold equal values, and extend the checking of syntactic equality to take that into account.

Using the pull request code, I get the following warning message for your code example with -Wcheck-bounds-decls:
```
>%clang% -fcheckedc-extension -Wcheck-bounds-decls tmp.c
tmp.c:5:21: warning: declared bounds for 'pa' may be invalid after initialization [-Wcheck-bounds-decls]
    _Array_ptr<int> pa : count(5) = (_Array_ptr<int>)&x;
                    ^~              ~~~~~~~~~~~~~~~~~~~
tmp.c:5:21: note: (expanded) declared bounds are 'bounds(pa, pa + 5)'
    _Array_ptr<int> pa : count(5) = (_Array_ptr<int>)&x;
                    ^~
tmp.c:5:37: note: (expanded) inferred bounds are 'bounds(&x, &x + 1ULL)'
    _Array_ptr<int> pa : count(5) = (_Array_ptr<int>)&x;
                                    ^~~~~~~~~~~~~~~~~~~
1 warning generated.
```

**Comment by dtarditi** [comment]
This question has been answered.
