### ISSUE TITLE
Missing DLL when building release .exe on clean machine

### ISSUE THREAD

**Issue by AnnaKornfeldSimpson** [Microsoft/checkedc-clang#494]
When I run the x64 .exe from the release page on a cleanly installed Windows machine and then try to run any "clang" command, it fails with the following error.

> C:/Program Files/CheckedC-LLVM/bin/clang.exe: error while loading shared libraries: ucrtbased.dll: cannot open shared object file: No such file or directory

One solution is to install any released version of the Windows 10 SDK, or the Universal C Runtime, via VS2017 "Get Tools and Features" installer.

**Comment by AnnaKornfeldSimpson** [comment]
ucrtbased.dll is the Debug build version of the ucrtbase.dll
ucrt is the Universal C Runtime, which Microsoft separated out from the rest of its C++ system in Visual Studio 2015.
It appears that building in Debug does not cause the debug versions of DLLs to be included.

**Comment by dtarditi** [comment]
Thanks for catching this!

I looked into the problem.  It turns out that our released binary is actually a debug build of the compiler   When building the compiler in our scripts, we are setting the CMAKE_BUILD_TYPE variable to Release.   This cmake variable is *ignored* when targeting a build system that supports multiple configurations by default (such as Visual Studio).  See this [page](https://cmake.org/cmake/help/v3.11/variable/CMAKE_BUILD_TYPE.html) from the CMake documentation We have to set the the configuration on the msbuild line using '/p:Configuration=Release' instead.

**Comment by dtarditi** [comment]
This is fixed.
