### ISSUE TITLE
Confusing error message when initializing _Array_ptr

### ISSUE THREAD

**Issue by abeln** [microsoft/checkedc-clang#680]
@mgrang and I noticed this today:

```C
_Array_ptr<int> foo = {1, 2, 3, 4};
```

Expected:
Either success, in which case we should be able to infer the bounds for `foo`,
or a failure with an error message explaining we don't support initialization via array literals
for _Array_ptr.

Actual:
```C
hello.c:16:28: error: initializing '_Array_ptr<int>' with an expression of incompatible type 'int'
    _Array_ptr<int> foo = {1, 2, 3, 4};
```

In particular, the `int` part is confusing because `{1, 2, 3, 4}` isn't an int.

**Comment by mgrang** [comment]
@abeln Thanks for reporting this. I will take a look into fixing this as time permits.

**Comment by dtarditi** [comment]
I think there is a misunderstanding of how C declarations with initializers work.    Given `T x = { … }`, the initializing expression `{...}` is used to initialize a value of type T.   The error is caused by the fact that the first element in the initializer isn't an array_ptr.

Here are some compiler examples and output:
```
int *foo = { 1, 2, 3, 4};

_Array_ptr<int> baz = { 1, 2, 3, 4};

tmp.c:1:14: warning: incompatible integer to pointer conversion initializing 'int *' with an expression of type 'int'
      [-Wint-conversion]
int *foo = { 1, 2, 3, 4};
             ^
tmp.c:1:17: warning: excess elements in scalar initializer
int *foo = { 1, 2, 3, 4};
                ^
tmp.c:3:25: error: initializing '_Array_ptr<int>' with an expression of incompatible type 'int'
_Array_ptr<int> baz = { 1, 2, 3, 4};
                        ^
2 warnings and 1 error generated.
```

For the first initializer, the compiler warns about a conversion of int to pointer.  It then warns about excess elements in an intializer for a scalar value.  The second warning is the real hint about what's going wrong.

For the second initializer, the compiler simply issues an error message about an incompatible type.  Note that the caret points at exactly the problematic code.

If I change the first initializer slightly to:
```
int *foo = { 3.14, 2, 3, 4};`
```
we see the same kind of error message as for _Array_ptr<int>:
```
tmp.c:1:14: error: initializing 'int *' with an expression of incompatible type 'double'
int *foo = { 3.14, 2, 3, 4};
             ^~~~
```
If you want to declare an array of 4 elements that is used to initialize an array_ptr, you need to write:
```
_Array_ptr<int> baz = (int[]) { 1, 2, 3, 4};
```
The expression (T[]) { ...} denotes [compound literal](https://en.cppreference.com/w/c/language/compound_literal) with array type.

While I agree the error message is confusing, I think this is not an issue that we'll fix right now.  It might be nice for clang to always recognize when someone has written an initializer with excess elements.  However, clang's behavior of stopping immediately at a type checking error is also reasonable.  For complex initializers, it is possible that the initializer is malformed, and that the warning about excess elements would be spurious.
